name: practica_guiada_2_riverpod_notificaciones_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  flutter_riverpod: ^3.0.3
  riverpod: ^3.0.3
  permission_handler: ^11.1.0  # Para manejar permisos del sistema operativo
  http: ^1.1.0                # Para peticiones HTTP
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
